flint.ui/src/main.js
flint.ui/src/views/flint/ConfigurationsRothc.vue
flint.ui/src/views/flint/Rothctemplate.vue
flint.ui/src/views/flint/configurations/lastyearcopy/RothcAvgairtempLastyearcopy.vue
flint.ui/src/views/flint/configurations/lastyearcopy/RothcOpenpanevapLastyearcopy.vue
flint.ui/src/views/flint/configurations/lastyearcopy/RothcPrescmLastyearcopy.vue
flint.ui/src/views/flint/configurations/lastyearcopy/RothcRainfallLastyearcopy.vue
flint.ui/src/views/flint/configurations/lastyearcopy/RothcSoilcoverLastyearcopy.vue
flint.ui/src/views/flint/configurations/monthavg/RothcAvgairtempMonthavg.vue
flint.ui/src/views/flint/configurations/monthavg/RothcOpenpanevapMonthavg.vue
flint.ui/src/views/flint/configurations/monthavg/RothcPrescmMonthavg.vue
flint.ui/src/views/flint/configurations/monthavg/RothcRainfallMonthavg.vue
flint.ui/src/views/flint/configurations/monthavg/RothcSoilcoverMonthavg.vue
flint.ui/src/views/flint/configurations/origin/RothcAvgairtempDataorigin.vue
flint.ui/src/views/flint/configurations/origin/RothcOpenpanevapDataorigin.vue
flint.ui/src/views/flint/configurations/origin/RothcPrescmDataorigin.vue
flint.ui/src/views/flint/configurations/origin/RothcRainfallDataorigin.vue
flint.ui/src/views/flint/configurations/origin/RothcSoilcoverDataorigin.vue

RothC has around 15 configurations, so maybe there's a better way to approach the configurations....
https://user-images.githubusercontent.com/58583793/126679416-12fe1c47-d682-4049-98af-bafdb5b0d135.mov

Configuration of rothc sim through forms

---

flint.ui/src/components/Headers/ExampleCardsRun2.vue

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
...

testing for new gcbm layout

---

flint.ui/src/views/flint/ConfigurationsRothc.vue

This was showing a grey screen, now it shows a list of config options.

Fix RothC config rendering

---

README.md

Added Code style section to the README.
Fixes #24

Added code style to README.

---

flint.ui/src/main.js

Fixed ESLint issue arising after merging #33 
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
...

Fixed ESLint syntax

---

flint.ui/package-lock.json
flint.ui/package.json

Fixes ESLint and prettier config
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
...

fixed Vue/ESLint prettier config

---

.gitignore
flint.ui/.gitignore
flint.ui/package-lock.json
package-lock.json

Fixing error caused by #44 as per developer notes - 
> Any dependency changes should happen in a separate branch
The error is still unclear but experimenting suggests that this is likely a problem with `package-lock.json`, so this should not be put in the `.gitignore` file.
...

Build fix at actions

---

flint.ui/src/store/index.js
flint.ui/src/store/modules/gcbm.js
flint.ui/src/views/flint/configurations/rothc/RothCInitSoil.vue

This PR adds GCBM configs to Vuex Store.

Add GCBM configs to store

---

flint.ui/src/layouts/GCBM.vue
flint.ui/src/views/gcbm/GCBMDashboard.vue

Added input field which is disabled if a title is not received. 
https://user-images.githubusercontent.com/58583793/129446890-8546c367-644c-44cc-be1c-b3256f94aa95.mov
...

Added input field for title for GCBM simulation 

---

flint.ui/package.json

Added moment.js as a dependency for calculating sim time in decimal notation
...

Added moment.js as dependency for sim time difference calculation

---

.github/workflows/codeql-analysis.yml

This PR:
- Adds CodeQL for static code analysis and quality checks

CI: add CodeQL for static code analysis and quality checks

---

.github/workflows/welcome-first-time-contrib.yml

Fixes: https://github.com/moja-global/FLINT-UI/issues/75#issuecomment-919731176

fix: Greeting GitHub Action

---

.github/workflows/lint.yml
docs/DevelopmentGuide/DevelopmentNotes.rst
docs/DevelopmentGuide/index.rst
flint.ui/src/components/Cards/CardInfoConfig.vue
flint.ui/src/components/Cards/CardInfoRun.vue
flint.ui/src/stories/Button.stories.js
flint.ui/src/stories/Button.vue

This PR:
- Adds Developer Notes documentation
- Lints existing codebase
- Adds a GHA for automated linting

Add Developer Notes + Lint Action

---

flint.ui/src/components/Cards/LandingPageCard.vue
flint.ui/src/components/Navbars/LandingPageNavbar.vue
flint.ui/src/views/Landing.vue
flint.ui/tailwind.config.js

This PR creates a new Landing Page as per latest design. Fixes #101 
Reviewers, test for:
- Responsiveness
- Code quality
- UI/UX and color accessibility
- Consistency with the Design
This implementation removes the `vue-tour` for landing page. Reason is because there description for each (point, GCBM etc.) is already provided with new design and thus becomes redundant to have tour for landing page.
Also, updated `tailwind.config` file to introduce `jit` mode and extending custom color.

Add Landing Page

---

flint.ui/Dockerfile

Fixes #108
@iamrajiv 
I am not sure about this addition, but I tried out this locally, it works
...

Bugfix: OpenSSL 3 incompatibility

---

README.md

These changes were extremely non-significant.

Non-significant.

---

flint.ui/src/components/Accordion/Accordion.vue
flint.ui/src/components/Accordion/AccordionItem.vue

Fixes #113 
This PR creates accordion component according to latest proposed design. In the subsequent PRs, we will add stories and tests related for the component as well. 
Made use of `slots` in order to implement this. 
Accordion component consists of 2 parts:
- Accordion Component (the wrapper around the accordion items)
- Accordion Items (which on click event triggers content inside it)
- The Accordion Items has two parts (slots) that are dynamic in terms of content
- Title/Header (can be a flexbox too)
- Content (can contain images etc. and it is flexible in terms of design)
```vue
<accordion>
<accordion-item>
<template class="flex justify-between" slot="accordion-trigger">
<h3 class="font-bold text-lg">Item 1</h3>
</template>
<template slot="accordion-content">
<span
>Lorem ipsum …
```

Add Accordion Component

---

flint.ui/Dockerfile
flint.ui/src/components/Datepicker/DatepickerPoint.vue
flint.ui/src/components/Datepicker/DatepickerRothC.vue
flint.ui/src/components/Navbars/LandingPageNavbar.vue
flint.ui/src/views/Landing.vue

This PR:
- Lints the codebase (chore)
- Makes landing page content more relevant (chore)
- Improves Dockerfile as per OCI image format (chore)

CHORE: Improve Dockerfile + Landing page content

---

README.md
docs/DevelopmentGuide/DevelopmentNotes.rst
flint.ui/cypress.json
flint.ui/package.json
flint.ui/tests/e2e/.eslintrc.js
flint.ui/tests/e2e/plugins/index.js
flint.ui/tests/e2e/specs/test.js
flint.ui/tests/e2e/support/commands.js
flint.ui/tests/e2e/support/index.js
flint.ui/yarn.lock

This PR is a part of fixing #123 issue. This PR adds required dependencies and adds basic setup for cypress in Vue.
The further testing setup can be included and handled in subsequent PRs. The issue #123 still persists as this PR just solves adding cypress testing framework to the project. 
Moreover, the `flint.ui/tests` folder is created that contains a standard folder structure for cypress testing. This can be altered as per our specification and requirements for the testing.

Scaffold Cypress E2E testing 

---

.github/workflows/docker-publish.yml
.github/workflows/main.yml

This PR
- Removes Docker build on CI and adds concurrency variable 
- Adds workflow to publish FLINT-UI image on every push

CI changes for FLINT-UI

---

.github/workflows/main.yml

This PR:
- Implements deps caching for `flint.ui`

CI refactor for FLINT-UI

---

.github/ISSUE_TEMPLATE/config.yml
README.md

Saw that we can add links in the issue template.
Added Slack's link to start off.

Issue template

---

flint.ui/public/index.html
flint.ui/src/components/Button/Button.vue
flint.ui/src/components/Cards/LandingPageCard.vue
flint.ui/src/components/Navbars/LandingPageNavbar.vue
flint.ui/src/index.css
flint.ui/src/views/Landing.vue

The UI changes requires as per the [new design](https://www.figma.com/proto/JXB1KKGWxD2dLR7dx2hqWS/Flint-UI?node-id=3%3A2&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=3%3A2) were made.
- The global font famity (DM Sans) was shifted from index.html to index.css, and `!important` was added because the font was not being applied. I don't completely understand why, but some other library might have added `Roboto, ...` as font family which takes higher precedence. `!important` solved this.
- The Button component made according to the new design was used.
- The landing banner and project's description had issues (padding of text, responsive text size, etc.)
- Navbar text color was changed acc. to the new design.
- LandingPageCard also had some styling issues which were fixed
The UI …

feat: update landing page UI according to the new design

---

flint.ui/src/components/Accordion/Accordion.vue
flint.ui/src/components/Accordion/AccordionItem.vue
flint.ui/src/views/flint/ConfigurationsRothC.vue

Fixes #162 
I have updated the RothC page as per the new Figma designs.  I am working on the accordion component, once the PR is merged others will be able to see the changes. With their feedback, I will make additional changes required.  I have not updated the `DatePickerRothC` component as per @YashKandalkar. 
Please review this PR @chicken-biryani

Update UI of `/flint/configurations/rothc` according to the new design

---

flint.ui/index.html
flint.ui/src/layouts/FLINT.vue
flint.ui/src/views/flint/ConfigurationsPoint.vue

Fixes #159 
Updated the UI of `/flint/configurations/point` according to the new UI design.
UI after the new changes:
Note:
The DatepickerPoint component is not updated in this issue, it will be covered in #160.

feat: update configurations point UI acc to new design

---

flint.ui/src/components/Sliders/Slider.vue
flint.ui/src/main.js
flint.ui/src/stories/Slider.stories.js

Closes #171 
Added the Slider component and a Slider.stories.js file for it.
Haven't added any color props because:
1. Ant design vue doesn't have any props to directly configure the color of track, dot, rail, etc.
2. These styles can be configured using scoped styles as necessary.
Open the Slider component in storybook.

feat: add Slider component, add a story for it.

---

flint.ui/src/layouts/GCBM.vue
flint.ui/src/views/flint/ConfigurationsRothC.vue
flint.ui/src/views/gcbm/GCBMDashboard.vue

Fixes #170 
- Adding header component to the `GCBM` page of the website. 
- Removed gradient property 
- Fixed small bug for the `rothc` page 
Thank You

Added header for the `GCBM` Page

---

flint.ui/src/components/Datepicker/DatepickerRothC.vue
flint.ui/src/views/flint/ConfigurationsRothC.vue
flint.ui/tailwind.config.js

I have changed the design of Rothc page and made it similar to Figma file of flint-UI 
Please include a summary of the change and which issue is fixed. 
Fixes #182 
...

Fixed padding and Positon of Text on Rothc page

---

flint.ui/src/components/Footer/Footer.vue

Fixes #190 
- Changed the background colour and made UI changes to make it look similar to Community Website footer. 
- Added new links that were missing from the footer component. 
- updated Moja Global logo to match design standards.

Updated Footer Component  

---

flint.ui/src/components/Navbars/LandingPageNavbar.vue

Fixes #188 
Added router link of a landing page on the logo
Click on the logo of the header section.

Added landing page link on logo

---

flint.ui/src/components/Footer/Footer.vue

Fixes #200 
Removed Inline styling and added style classes inside <style scoped> tag
- Removed Inline styles
- Added classes for styling
- Changed name for exporting the footer component

Added style classes and changed export name of the component

---

flint.ui/src/components/Datepicker/Datepicker.vue
flint.ui/src/stories/DatePicker.stories.js

Adds a new Datepicker component (#174). This component can now be used in DatepickerPoint and DatepickerRothC components.
Open storybook and see the Datepicker component
Let me know if any changes are required!
Closes #174

Add Datepicker component

---

README.md

Signed-off-by: Axit Patel <patelakshit2025@gmail.com>
Fixes #211 
I have added Ant Design Vue in readme file
...

Added Ant Design Vue in read me file

---

flint.ui/src/components/Datepicker/DatepickerRothC.vue

Fixes #210 
Required changes has been done
...

Updated DatepickerRothC.vue file

---

flint.ui/src/components/FileUpload/FileUpload.vue
flint.ui/src/components/Sliders/Toggle.vue
flint.ui/src/views/gcbm/GCBMRun.vue
flint.ui/src/views/gcbm/GCBMUpload.vue

Fixes #198 
I have changed the theme of GCBM Step 1 2. 
I have also added navbar to both of them.

feat: changed theme of GCBM Step1 2 as per new UI

---

flint.ui/src/components/FileUpload/FileUpload.vue
flint.ui/src/components/Footer/Footer.vue
flint.ui/src/routes/routes.js
flint.ui/src/views/Errorpage.vue
flint.ui/src/views/gcbm/GCBMRun.vue
flint.ui/src/views/gcbm/GCBMUpload.vue
flint.ui/yarn.lock

Initially, there was no 404 Error Page on an invalid URL
Go to : http://localhost:8000/invalidurl
...
On Hovering 
@HarshCasper @chicken-biryani  can you please once review it :)

feat: Added a new Error Page

---

README.md
flint.ui/src/components/Footer/Footer.vue

Fixes #218 
Automate year in the footer section

Automate year

---

flint.ui/package.json
flint.ui/yarn.lock

Fixes https://github.com/moja-global/FLINT-UI/issues/235

FIX: Fix the Docker Build

---

flint.ui/src/views/flint/TablePoint.vue
flint.ui/src/views/flint/TableRothC.vue

#249 
- Added header component to both the pages. 
- Changed the UI design to match the website.

Updated data visualisation table page for `Point` and `RothC`

---

flint.ui/src/components/Datepicker/DatepickerRothC.vue

I updated the  RothC DatePicker Component in the [ConfigurationsRothC.vue](https://github.com/moja-global/FLINT-UI/issues/flint.ui%5Csrc%5Cviews%5Cflint%5CConfigurationsRothC.vue) file to use Ant Design Implementation. It was previously built with pure CSS implementation.
Fixes: #245 
none

refactor: updated datepicker in RothC configuration page with ant design

---

flint.ui/src/components/Cards/CardInfoConfig.vue
flint.ui/src/components/Cards/CardInfoRun.vue
flint.ui/src/index.css
flint.ui/src/views/flint/RothCTemplate.vue
flint.ui/src/views/flint/TablePoint.vue
flint.ui/src/views/gcbm/GCBMDashboard.vue
flint.ui/src/views/gcbm/GCBMRun.vue
flint.ui/src/views/gcbm/GCBMUpload.vue

Please include a summary of the change and which issue is fixed. 
...

fix: difference in hover effects of button

---

flint.ui/src/components/Datepicker/DatepickerPoint.vue
flint.ui/src/components/Datepicker/DatepickerRothC.vue
flint.ui/src/views/flint/ConfigurationsRothC.vue
flint.ui/src/views/flint/RothCTemplate.vue
flint.ui/src/views/flint/TablePoint.vue
flint.ui/src/views/flint/TableRothC.vue

I updated the Point DatePicker Component in the [ConfigurationsPoint.vue](https://github.com/moja-global/FLINT-UI/issues/flint.ui%5Csrc%5Cviews%5Cflint%5CConfigurationsPoint.vue) file to use Ant Design Implementation. It was previously built with pure CSS implementation.
Fixes: #244
none

Refactor date picker point

---

flint.ui/src/store/modules/rothc.js
flint.ui/src/views/flint/ConfigurationsRothC.vue
flint.ui/src/views/flint/PointOutput.vue
flint.ui/src/views/flint/RothCOuterTable.vue
flint.ui/src/views/flint/RothCOutput.vue
flint.ui/src/views/flint/Table.vue
flint.ui/src/views/flint/TableRothC.vue

RothC output was not properly visible.
Go to RothC config, click Run, then RothC Output Table.

fix RothC output 

---

flint.ui/src/components/Cards/CardInfoConfig.vue
flint.ui/src/components/Cards/CardInfoRun.vue
flint.ui/src/components/Cards/LandingPageCard.vue

I have changed card component from Vue 2 to Vue 3 
@HarshCasper may you please once review this.

feat: Changed Card component from Vue 2 to Vue 3

---

flint.ui/src/components/Navbars/LandingPageNavbar.vue
flint.ui/src/components/Vuelayers/Map.vue
flint.ui/src/components/Vuelayers/Maptest.vue

I have changed Maps, Navbar component from Vue 2 to Vue 3
@HarshCasper may you please once review this.

Changed Maps, Navbar from Vue 2 to Vue 3

---

flint.ui/src/components/Slider/Slider.vue
flint.ui/src/components/Slider/Toggle.vue

I have changed button component from Vue 2 to Vue 3
@HarshCasper may you please once review this.

feat: Changed Slider component from Vue 2 to Vue 3

---

flint.ui/src/components/Cards/LandingPageCard.vue
flint.ui/src/views/Landing.vue

Added cards to Point, RothC and GCBM sections of landing page
Fixes #308

Added cards to Point, RothC and GCBM sections of landing page

---

flint.ui/src/components/Prompts/ConfirmConfig.vue
flint.ui/src/components/Prompts/ConfirmRun.vue
flint.ui/src/components/Stepper/StepperGCBM.vue
flint.ui/src/components/Stepper/StepperPoint.vue
flint.ui/src/components/Stepper/StepperRothc.vue

I have changed Stepper, Prompt component from Vue 2 to Vue 3 
@HarshCasper may you please once review this.

feat: Changed Stepper, Prompt from Vue 2 to Vue 3

---

flint.ui/src/components/Datepicker/DatepickerGCBM.vue
flint.ui/src/components/GCBM/GCBMConfigurations.vue
flint.ui/src/components/GCBM/GCBMLanding.vue
flint.ui/src/components/GCBM/LocalDomain.vue
flint.ui/src/components/Stepper/StepperStatic.vue
flint.ui/src/layouts/GCBM.vue
flint.ui/src/routes/routes.js
flint.ui/src/store/modules/gcbm.js
flint.ui/src/views/Landing.vue
flint.ui/src/views/flint/ConfigurationsRothC.vue
flint.ui/src/views/gcbm/GCBMDashboard.vue

Added a Sidebar for the top-level configs in GCBM. Added a LocalDomain component. Still a WIP.
Click on Explore in the GCBM card on the landing page.
Nothing is working yet, I'll work on adding sub-menus in each config as I progress through them in the upcoming weeks. 
The `/gcbm/configurations` page will give an overview of the simulation, and the configs will have their separate paths. 
For eg.: `gcbm/configurations/local-domain` for the Local Domain config.

feat: add Sidebar, LocalDomain in GCBM. WIP.

---

flint.ui/src/components/GCBM/Configurations/LocalDomain.vue
flint.ui/src/components/GCBM/Configurations/Modules.vue
flint.ui/src/components/GCBM/Configurations/Variables.vue
flint.ui/src/layouts/GCBM.vue
flint.ui/src/routes/routes.js
flint.ui/src/store/modules/gcbm.js
flint.ui/src/views/gcbm/GCBMDashboard.vue

Adds the Variables config editor.
The names of the groups (Variables, Ranges & Rates, Boundaries & Land Class) can be changed later as needed.
go to /gcbm/configurations/variables

feat: add Variables config for GCBM run

---

flint.ui/src/views/flint/Table.vue

Please include a summary of the change and which issue is fixed. 
...

refactor: Migrated Table.vue to Vue 3

---

flint.ui/src/components/Navbars/LandingPageNavbar.vue
flint.ui/src/views/flint/ConfigurationsPoint.vue

Fixes #333 .
- Migrates `ConfigurationsPoint` component to Composition API.
- Fixes a lint error in `LandingPageNavbar`.

refactor: ConfigurationsPoint to Composition API

---

flint.ui/src/views/flint/ConfigurationsPoint.vue
flint.ui/src/views/flint/PointOuterTable.vue

Fixes #335.
- Migrates `PointOuterTable` component to Composition API.
- Fixes a bug in `ConfigurationsPoint` view which caused errors while rendering the table.

refactor: PointOuterTable to Composition API

---

flint.ui/src/views/flint/ConfigurationsRothC.vue
flint.ui/src/views/flint/RothCOuterTable.vue
flint.ui/src/views/flint/RothCOutputContainer.vue

**FIxed issue: #337** 
**1. migrated RothCOuterTable to Vue 3 (Composition API) 
2. renamed RothCOuterTable to  RothCOuterContainer**

Feat : migrated component to Vue 3 (Composition API)

---

flint.ui/package.json
flint.ui/src/components/Cards/LandingPageCard.vue
flint.ui/src/views/Errorpage.vue
flint.ui/src/views/flint/ConfigurationsPoint.vue
flint.ui/src/views/flint/ConfigurationsRothC.vue
flint.ui/yarn.lock

Replacing components of Flint UI with @moja-global/mojaglobal-ui library

Replacing Button component of Flint UI with @moja-global/mojaglobal-ui library

---

flint.ui/src/components/Footer/Footer.vue

Replaced footer component of Flint UI with @moja-global/mojaglobal-ui library

Replaced footer component of Flint UI with @moja-global/mojaglobal-ui library

---

README.md

Updated number of contributors needed in the README

---

.github/PULL_REQUEST_TEMPLATE.md

Fixes #371 
Please include a summary of the change and which issue is fixed. 
...

PR template improved

---

.devcontainer/devcontainer.json

This PR fixes https://github.com/moja-global/FLINT-UI/issues/404

Add Vue3 syntax highlighting extension

---

flint.ui/src/components/ConfigurationsRothC/RothCInitSoil.vue

fix : Accordian visual glitch in RothC

---

flint.ui/src/views/flint/ConfigurationsRothC.vue

This PR fixes #384 
Replaced the  current accordion component with UI-library's accordion component
Changes are visible at : /flint/configurations/rothc

feat : Replaced accordion component with Ui-library's

---

flint.ui/src/components/Vuelayers/Maptest.vue
flint.ui/src/views/flint/ConfigurationsPoint.vue

Added Modal component to fix the UI of a map in the Point module
This pr fixes #266 
Earlier:
Now:

Added modal component for map

---

flint.ui/src/views/flint/ConfigurationsPoint.vue

Signed-off-by: Sambhav Gupta <sambhavgupta0705@gmail.com>
replaced the notification component with moja global UI library
This PR fixes #
#393 
Please write instructions so we can verify your changes.
...

feat: replaced notification component in point 

---

flint.ui/src/store/modules/gcbm.js
flint.ui/src/views/gcbm/GCBMConfigurations.vue
flint.ui/src/views/gcbm/GCBMCreate.vue
flint.ui/src/views/gcbm/GCBMRun.vue
flint.ui/src/views/gcbm/GCBMUpload.vue

- Replaces current notification component in GCBM with UI Library's notification component
This PR fixes #439

feat: replace current notification component in GCBM with UI Library's notification component

---

flint.ui/src/components/Cards/CardInfoRun.vue

Signed-off-by: Abhilipsa Sahoo <abhilipsasahoo03@outlook.com>
- Replaces current notification component with UI-Library's notification component in CardInfoRun.vue file
This PR fixes #395  
...

feat: Replace notification component in CardInfoRun.vue

---

flint.ui/package.json
flint.ui/src/components/Navbars/LandingPageNavbar.vue
flint.ui/yarn.lock

Signed-off-by: rahulsh18 <rahulsharmaa1805@gmail.com>
This PR fixes #383

replaced ant design navbar with ui library navbar component

---

flint.ui/src/components/Datepicker/DatepickerPoint.vue

Signed-off-by: Karan Singh Thakur <karanthakur.work@gmail.com>
This PR is a follow-up for #432 
Please write instructions so we can verify your changes.
...

feat: updated notification title

---

flint.ui/src/components/Cards/LandingPageCard.vue

Signed-off-by: Abhilipsa Sahoo <abhilipsasahoo03@outlook.com>
This PR fixes #391 
- Replaced current card component with UI-Library's card component in LandingPageCard.vue
- It's responsive!
...

feat: replaced card component in LandingPageCard.vue
