.github/workflows/main.yml
This is a basic build check to test out Github Actions. If it builds in a container we assume it'll build elsewhere.
=> Add client build to Github Actions

docker-compose.yml
As per #48, Storybook is not working as intended and takes up significant amount of time to build in `docker-compose`. We may come later after updating all the components. 
...
=> Temporarily halting storybook in docker-compose

flint.ui/src/components/Datepicker/DatepickerPoint.vue, flint.ui/src/components/Datepicker/DatepickerRothC.vue
#57 added `moment.js` lib to calculate time difference between simulation runs. Here's the preview for the same - 
https://user-images.githubusercontent.com/58583793/129698307-0d75944f-340c-433a-aa16-40a39ae133f1.mov
...
=> Using moment.js to get the difference b/w start and end dates in Datepicker component

flint.ui/src/store/modules/gcbm.js, flint.ui/src/views/gcbm/GCBMDashboard.vue
Add feature: Create new GCBM job with a custom Title!
In this image `yoyo` is a custom title for the GCBM job!
This list can be obtained by making a GET request to http://127.0.0.1:8081/gcbm/list
`Set title` button store the job title in the state, while `Create run` sends the POST request to the API.
=> add feature: create new GCBM job!

flint.ui/package-lock.json, flint.ui/package.json, flint.ui/src/components/Datepicker/DatepickerPoint.vue, flint.ui/src/components/Datepicker/DatepickerRothC.vue, flint.ui/src/components/Sidebar/Sidebar.vue, flint.ui/src/routes/routes.js, flint.ui/src/store/modules/point.js, flint.ui/src/store/modules/rothc.js, flint.ui/src/views/flint/TablePoint.vue, flint.ui/src/views/flint/TableRothC.vue
Displays the received Point and RothC outputs as a grid/spreadsheet.
Introducing [RevoGrid](https://revolist.github.io/revogrid/) for rendering the outputs as a spreadsheet.
https://user-images.githubusercontent.com/13800316/129945924-53bfe6b4-b817-45ed-94ce-ecad137e20aa.mp4
=> Add feature: Display Point & RothC output

flint.ui/src/views/Landing.vue
Currently, the landing page of FLINT UI has black text color with example content.
=> fix: Refactor text color and content of landing page

flint.ui/.babelrc, flint.ui/package-lock.json, flint.ui/package.json, flint.ui/src/components/Sidebar/Sidebar.vue, flint.ui/src/components/Sliders/Toggle.vue, flint.ui/src/components/Stepper/StepperGCBM.vue, flint.ui/src/routes/routes.js, flint.ui/src/store/modules/gcbm.js, flint.ui/src/store/modules/point.js, flint.ui/src/stories/Button.stories.js, flint.ui/src/stories/Button.vue, flint.ui/src/views/gcbm/GCBMDashboard.vue, flint.ui/src/views/gcbm/GCBMRun.vue, flint.ui/src/views/gcbm/GCBMUpload.vue
- The `GCBM` sim run involved checking the status of the ongoing simulation and once the simulation is complete, users can `download` the result. With the toggle `enable`, this checks for the simulation status every `30 secs`, and auto downloads when the simulation is complete.
- console.log statements in production environment is considered a bad practice and should be removed, the `babel-plugin-transform-remove-console` helps take care of that.
https://user-images.githubusercontent.com/58583793/132050502-d8d1f5a2-cd7b-49e2-b97f-203d21391da0.mov
...
=> Auto downloading simulation on toggle / Removing console.log statements on production build

flint.ui/src/components/Cards/CardInfoConfig.vue, flint.ui/src/components/Cards/CardInfoRun.vue
The size of cards is not proper because of the wrong alignment of `{{ cardDescription }}`.
=> fix: Irregular card size

flint.ui/src/components/Button/Button.vue, flint.ui/src/stories/Button/Button.stories.js
This PR addresses [#111 ](https://github.com/moja-global/FLINT-UI/issues/111). It adds the Button component as per the latest design.
- Ensure the `Button` component is in `flint.ui/src/components/Button/Button.vue`
- Ensure the `Button` component has required props
- Ensure styling as per the Figma designs
- Ensure the proper Hover state and transition effect on hover
- To test the  `<Button />` component you may Import it in `flint.ui/src/components/Cards/CardInfoRun.vue` and use it like `<Button btnText="Run" @onClick="showConfirmRunModal()" />` then navigate to http://localhost:8000/flint/dashboard
- Verify the `Button` displays and opens the model on click
=> Created Button component

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
This PR:
- Adds a `devcontainer.json`
- Adds a Dockerfile to be built with `.devcontainer`
This PR would facilitate all the developers to start building inside a development container with a well-defined tool and runtime stack.
=> FEAT: Add a dev container for Docker development

flint.ui/src/components/Navbars/LandingPageNavbar.vue
For now, the navbar only shows Documentation and Github. The new "Contact Us" element will be redirected to the organisation's email.
#133 
...
=> Add Contact Us to Navbar

flint.ui/src/components/Datepicker/DatepickerRothC.vue
This PR Fixes #208 
The date picker in RothC was having a common variable for start date and end date, if someone selects start date then end date was also changing and vice versa.
Go to RothC component, select start or end date using the date picker. It will not reflect the change in another date.
=> Correction in datepicker for start and end dates

flint.ui/src/views/flint/PointOutput.vue, flint.ui/src/views/flint/TablePoint.vue
Fixes #230 
when we click on the point output table option on the simulator page it leads to 
clicking on visualize on graph leads to 
in this I have removed the visualize on graph button and print the graph on the previous page 
@HarshCasper @chicken-biryani can you please once review it :)
=> feat: removed the visualize on graph button

flint.ui/src/views/flint/ConfigurationsRothC.vue
This pr fixes the Extra width of configuration cards of RothC  #237 
...
=> fix: extra width fixes of configuration cards of RothC 

flint.ui/src/components/Datepicker/DatepickerPoint.vue, flint.ui/src/views/flint/ConfigurationsPoint.vue
Fixes #207 
The simulation length was not changing dynamically. Resolved errors to make it change based on selected start and end dates.
1) Go on the Point page.
2) Change start or end dates.
3) Check the updated simulation length.
=> Updated simulation length in Point dynamically

flint.ui/src/views/flint/ConfigurationsRothC.vue, flint.ui/src/views/flint/TablePoint.vue
Content on the RothC page was not properly aligned. It is now aligned properly.
fixes #226.
...
@all-contributors please add @timonwa for bug
=> Text alignment fix on RothC page.

flint.ui/src/views/flint/ConfigurationsRothC.vue, flint.ui/src/views/flint/RothCTemplate.vue
Added user-friendly text to display for the user to know what the configuration parameters means for the RothC simulation.
Just launch vue server and go to `http://localhost:8001//flint/configurations/rothc`
=> Add description text to configuration parameters cards for RothC

flint.ui/src/components/Navbars/LandingPageNavbar.vue
The navbar spacing on the left and right now align properly with other contents on the pages. fixes #268
=> refactor: fixed navbar spacing bug

docs/conf.py, docs/requirements.txt
Updated the FLINT-UI documentation theme to Furo to match it with the main documentation of Moja Global. It Closes #274 
...
=> Updated Sphinx theme to Furo to match it with main documentation

README.md, flint.ui/package.json
Removes Google Maps as a dependency, since we don't use it anymore. Should skim off some of the `node_modules` bloat. Also replaces the mention of Google Maps with OpenLayers in README.
N/A
N/A
=> docs+build: Replace Google Maps with OpenLayers

flint.ui/src/components/Footer/Footer.vue, flint.ui/src/components/Stepper/StepperGCBM.vue, flint.ui/src/routes/routes.js, flint.ui/src/views/Landing.vue
This PR:
- Makes `StepperGCBM` based on Ant Design rather than Vue Material (We were having problems with Vue Material on Vue3).
- Fixes a bug where hovering over social media icons would result in a transparent background.
- Fixes a typo on the Landing page.
- Visit `/gcbm/dashboard` and click on Step 1 or Step 3 (Step 2 is broken; see below).
- Hover over social icons in footer.
**Note:** `GCBMUpload` is known to be broken (does not load) because we're using Vue2's Dropzone. Once we convert that to Vue3, we should be able to access it. Also, the stepper design can be refactored further to use icons and make it more responsive.
=> fix+refactor: convert StepperGCBM to Ant Design

flint.ui/package.json, flint.ui/yarn.lock
Error-stack-parser, parses and extracts function names, URLs, line numbers, and column numbers from the given Error's stack as an Array of [StackFrame](http://git.io/stackframe)s.
=> BugFix: Error-stack-parser installed to Fix CI build failures

flint.ui/src/App.vue, flint.ui/src/components/Stepper/StepperGCBM.vue, flint.ui/src/views/Errorpage.vue, flint.ui/src/views/Landing.vue, flint.ui/src/views/flint/ConfigurationsPoint.vue, flint.ui/src/views/flint/ConfigurationsRothC.vue, flint.ui/src/views/gcbm/GCBMDashboard.vue, flint.ui/src/views/gcbm/GCBMRun.vue, flint.ui/src/views/gcbm/GCBMUpload.vue
1. Until now, we were rendering the `Footer` and `LandingPageNavbar` components in every component. These can be moved to the root component `App` to eliminate redundancy. 
2. A very minor bug existed in `StepperGCBM` which would cause the currently selected step to appear hollow. This PR fixes the bug. Now the step is correctly highlighted with a blue color.
For the bug fix: go to `/gcbm/dashboard` and click on any of the steps.
=> fix+refactor: Render Navbar and Footer in root component

README.md, flint.ui/package.json, flint.ui/src/components/Cards/CardInfoRun.vue, flint.ui/src/components/Footer/Footer.vue, flint.ui/src/components/Stepper/StepperStatic.vue, flint.ui/src/main.js, flint.ui/src/views/flint/ConfigurationsRothC.vue, flint.ui/src/views/flint/RothCTemplate.vue, flint.ui/src/views/gcbm/GCBMDashboard.vue, flint.ui/src/views/gcbm/GCBMRun.vue, flint.ui/src/views/gcbm/GCBMUpload.vue, flint.ui/yarn.lock
This PR converts all FontAwesome icons to Ant Design icons. This way, we can get rid of the dependency entirely. The icons also fit better with the rest of the components oriented towards Ant Design. Most of the icons are the exact same, while some of them resemble the previous icons as closely as possible.
It also fixes the bug where `RothC` accordion arrows were not rendered properly. Now they work and rotate as intended. 
Visit various endpoints throughout the web application to see the new icons on the components.
Icons that have been converted:
- `fa-play-circle` --> `PlayCircleOutlined`
- `fa-envelope` --> `MailFilled`
- `fa-twitter` --> `TwitterCircleFilled`
- `fa-linkedin` --> `LinkedinFilled`
- `fa-plus` --> `PlusOutlined`
- `fa-arrow-right` --> `ArrowRightOutlined`
- `fa-file` …
=> refactor: Migrate from Fontawesome to AntD icons

flint.ui/package.json, flint.ui/src/components/Cards/CardInfoRun.vue, flint.ui/src/components/Datepicker/DatepickerPoint.vue, flint.ui/src/components/Datepicker/DatepickerRothC.vue, flint.ui/src/components/FileUpload/FileUpload.vue, flint.ui/src/main.js, flint.ui/src/store/modules/gcbm.js, flint.ui/src/store/modules/point.js, flint.ui/src/store/modules/rothc.js, flint.ui/src/views/gcbm/GCBMRun.vue, flint.ui/src/views/gcbm/GCBMUpload.vue, flint.ui/yarn.lock
Fixes #314.
The first commit replaces `Toast` invocations with Ant Design `Notifications`. The notification styles and duration are almost exact. A new UX oriented change is that `error` and `warning` notifications now last longer (4 seconds typically) than `success` or `info`  notifications (2 seconds typically) since error messages might take more time to read and digest.
The second commit removes `vue-toastification` dependency from `package.json`.
- A reliable way is to head over to `/gcbm/upload` to test the info notification.
- The Run/Status/Download buttons on `/gcbm/run` can also be pressed which should display notifications. See below for expected output.
`/gcbm/upload`
`/gcbm/run`
=> refactor: Migrate from Toasts to Notifications

flint.ui/src/views/flint/ConfigurationsRothC.vue, flint.ui/src/views/flint/RothCOuterTable.vue
Fixes #318.
- Migrates `ConfigurationsRothC` view to Composition API.
- Uses the intrinsic Accordian arrow, instead of the Ant Design icon.
- The second commit fixes a bug where the RothC table wouldn't render. This happened because `Date` was unable to parse our date format. The fix involves using `dayjs` with a custom format specifier to parse the date first and then constructing the `Date` object.
=> refactor: ConfigurationsRothC to Composition API

flint.ui/src/store/modules/point.js, flint.ui/src/views/flint/ConfigurationsPoint.vue
Fixes #349.
This PR:
- Adds a check to detect if pool values are unchanged before running a simulation.
- Adds a little feature to toggle the table when `Point Output Table` button is clicked.
Go over to `/flint/configurations/point`. Then, there's really four essential checks:
1. Check if you can run the simulation successfully for the very first time, using an arbitrary input.
2. Check if you can run the simulation a second time, with an arbitrary input.
3. Check if you can can run the simulation with the **same values** as in Step 2. This should pop up a modal. If you click OK, it should dispatch the run.
4. Check if you can run the simulation with arbitrary inputs, again. This should fly without any warnings.
These checks simulate some scenarios that could happen when a user runs the …
=> feat: A check to detect if pool values are unchanged

flint.ui/src/views/flint/ConfigurationsPoint.vue
Fixes #353.
Fixes a bug where the page would crash ungracefully if `Point Output Table` button was clicked before running the simulation. Log is in the bug report. 
To fix this - we check if the simulation has been ran before, using the `firstRun` state variable. If not, we display an error notification and return early.
Head over to `/flint/configurations/point` and click on `Point Output Table` **without** running the simulation first. This should pop up an error notification.
=> Fix: Crash while displaying point simulation result

flint.ui/src/store/modules/rothc.js, flint.ui/src/views/flint/ConfigurationsRothC.vue
Fixes #387
Fixes a bug where the page would crash ungracefully if the  Run button quickly followed by the Point Output Table button, the whole thing crashes without any warnings or indicators. A log is in the bug report.
To fix this - we check if the simulation has been ran before, using the firstRun state variable. If not, we display an error notification and return early.
Head over to  /flint/configurations/rothc and click on Point Output Table without running the simulation first. This should pop up an error notification.
=> Fixes RothC page crashes if table is displayed before simulation finishes
